---
- name: Enable mod_header
  apache2_module: state=present name=headers

- name: Copy CKAN Apache Conf file
  template: src=ckan_conf.j2 dest=/etc/apache2/sites-available/ckan_default.conf

- name: Symlink CKAN Apache file
  file: src=/etc/apache2/sites-available/ckan_default.conf dest=/etc/apache2/sites-enabled/ckan_default.conf state=link

- name: Open port to CKAN
  lineinfile: dest=/etc/apache2/ports.conf line="NameVirtualHost *:8800" state=absent

- name: Open port to CKAN
  lineinfile: dest=/etc/apache2/ports.conf line="Listen 8800" state=present

- name: Modify ports
  lineinfile: dest=/etc/apache2/ports.conf regexp="Listen 80" line="Listen 8080"

- name: Copy Datapusher Apache Conf file
  template: src=datapusher_conf.j2 dest=/etc/apache2/sites-available/datapusher.conf

- name: Symlink Datapusher Apache Conf file
  file: src=/etc/apache2/sites-available/datapusher.conf dest=/etc/apache2/sites-enabled/datapusher.conf state=link

- name: Remove default Apache conf file
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Start Jetty
  service: name=jetty8 state=restarted

- name: Start Apache
  service: name=apache2 state=restarted

